// "Bobby Pierce" appears twice, consecutively, in the source data. This may
// reflect two separate (non-consecutive) terms rather than a transcription
// error on this end — flagged here for chapter confirmation before publish.
export type PastPresident = {
  name: string;
  badge?: string;
};

export const pastPresidents: PastPresident[] = [
  { name: "Jessie O. Richards" },
  { name: "William H. Mitchell" },
  { name: "Rudolph Moses" },
  { name: "C.C. Haydel" },
  { name: "A.P. Tureaud" },
  { name: "Edward M. Coleman" },
  { name: "Percy P. Creuzot" },
  { name: "Ernest Cherrie" },
  { name: "W.R. Adams" },
  { name: "G.B. Talbert" },
  { name: "W.E. Belton" },
  { name: "Ferdinand Rousseve" },
  { name: "W. Haydel" },
  { name: "Benson M. Boutte" },
  { name: "Willard Dumas" },
  { name: "Marcus Neustadter Jr." },
  { name: "Anthony M. Rachal Jr." },
  { name: "Ernest N. Morial", badge: "23rd General President" },
  { name: "Maurice Prevost" },
  { name: "Emmett W. Bashful" },
  { name: "William R. Adams" },
  { name: "Walter King" },
  { name: "Charles L. DeLay" },
  { name: "Charles C. Teamer Sr.", badge: "27th General President" },
  { name: "Rudolph Deteige" },
  { name: "Ellis Smith" },
  { name: "Gerald V. Williams" },
  { name: "Bobby Pierce" },
  { name: "Ivan L.R. Lemelle" },
  { name: "Bobby Pierce" },
  { name: "Howard L. Rodgers III" },
  { name: "Marion B. Bracy", badge: "Southwestern Regional Vice President" },
  { name: "Joseph K. Byrd" },
  { name: "Ernest Jones" },
  { name: "Joshua Williams Jr.", badge: "Louisiana District Director" },
  { name: "Merlin Gilyot" },
  { name: "Wayne E. Woods" },
  { name: "Joe M. Ricks Jr." },
  { name: "Omar K. Mason" },
  { name: "Glenn Sergeant Sr." },
  { name: "Bernard Blair" },
  { name: "Gilbert A. Jones" },
  { name: "Keith V. Dillon Sr." },
  { name: "Reginald A. Starks" },
  { name: "Kevin O'Bryan Guidry" },
  { name: "Tyronne Walker" },
  { name: "Jonathan Stewart" },
  { name: "Percy Manson" },
  { name: "Howard Rodgers, IV" },
  { name: "Robert Carter, III" },
  { name: "Brian Turner" },
];
