// "Bobby Pierce" appears twice, consecutively, in the source data. This may
// reflect two separate (non-consecutive) terms rather than a transcription
// error on this end — flagged here for chapter confirmation before publish.
export const pastPresidentsFootnote = {
  morial: "23rd General President of Alpha Phi Alpha Fraternity, Inc.",
  teamer: "27th General President of Alpha Phi Alpha Fraternity, Inc.",
};

export const pastPresidents: string[] = [
  "Jessie O. Richards",
  "William H. Mitchell",
  "Rudolph Moses",
  "C.C. Haydel",
  "A.P. Tureaud",
  "Edward M. Coleman",
  "Percy P. Creuzot",
  "Ernest Cherrie",
  "W.R. Adams",
  "G.B. Talbert",
  "W.E. Belton",
  "Ferdinand Rousseve",
  "W. Haydel",
  "Benson M. Boutte",
  "Willard Dumas",
  "Marcus Neustadter Jr.",
  "Anthony M. Rachal Jr.",
  "Ernest N. Morial *",
  "Maurice Prevost",
  "Emmett W. Bashful",
  "William R. Adams",
  "Walter King",
  "Charles L. DeLay",
  "Charles C. Teamer Sr. **",
  "Rudolph Deteige",
  "Ellis Smith",
  "Gerald V. Williams",
  "Bobby Pierce",
  "Ivan L.R. Lemelle",
  "Bobby Pierce",
  "Howard L. Rodgers III",
  "Marion B. Bracy",
  "Joseph K. Byrd",
  "Ernest Jones",
  "Joshua Williams Jr.",
  "Merlin Gilyot",
  "Wayne E. Woods",
  "Joe M. Ricks Jr.",
  "Omar K. Mason",
  "Glenn Sergeant Sr.",
  "Bernard Blair",
  "Gilbert A. Jones",
  "Keith V. Dillon Sr.",
  "Reginald A. Starks",
  "Kevin O'Bryan Guidry",
  "Tyronne Walker",
  "Jonathan Stewart",
  "Percy Manson",
  "Howard Rodgers, IV",
  "Robert Carter, III",
  "Brian Turner",
];
